import type { Command } from "commander";
import type { MemoireEngine } from "../engine/core.js";
import { checkCapabilities, formatCapabilityError } from "../engine/capabilities.js";

export interface PullPayload {
  status: "completed" | "failed";
  figma: {
    connected: boolean;
  };
  designSystem: {
    tokens: number;
    components: number;
    styles: number;
  };
  specs: {
    autoGenerated: number;
    total: number;
  };
  elapsedMs: number;
  error?: string;
}

export function registerPullCommand(program: Command, engine: MemoireEngine) {
  program
    .command("pull")
    .description("Pull design system from connected Figma file")
    .option("--json", "Output pull results as JSON")
    .action(async (opts: { json?: boolean }) => {
      const start = Date.now();
      await engine.init();

      // Check capabilities before attempting connection
      const caps = checkCapabilities("pull", {
        figma: engine.figma?.isConnected ?? false,
        ai: !!process.env.ANTHROPIC_API_KEY,
        specs: false,
        generatedCode: false,
        research: false,
        daemon: false,
      });

      if (!caps.ok && !engine.figma?.isConnected) {
        // Try to connect first
        try {
          await engine.ensureFigmaConnected();
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          if (opts.json) {
            const payload: PullPayload = {
              status: "failed",
              figma: { connected: false },
              designSystem: { tokens: 0, components: 0, styles: 0 },
              specs: { autoGenerated: 0, total: 0 },
              elapsedMs: Date.now() - start,
              error: msg,
            };
            console.log(JSON.stringify(payload, null, 2));
            process.exitCode = 1;
            return;
          }
          console.error(formatCapabilityError(caps, "pull"));
          process.exitCode = 1;
          return;
        }
      }

      if (!opts.json) console.log("\n  Pulling design system...\n");
      await engine.pullDesignSystem();

      const specs = await engine.registry.getAllSpecs();
      const autoSpecs = specs.filter((s) => s.type === "component" && s.tags?.includes("auto-generated"));
      const ds = engine.registry.designSystem;

      const payload: PullPayload = {
        status: "completed",
        figma: { connected: true },
        designSystem: {
          tokens: ds.tokens.length,
          components: ds.components.length,
          styles: ds.styles.length,
        },
        specs: {
          autoGenerated: autoSpecs.length,
          total: specs.length,
        },
        elapsedMs: Date.now() - start,
      };

      if (opts.json) {
        console.log(JSON.stringify(payload, null, 2));
        return;
      }

      console.log(`\n  Done. Design system saved to .memoire/design-system.json`);
      if (autoSpecs.length > 0) {
        console.log(`  Auto-generated ${autoSpecs.length} component specs — run \`memi generate\` to create code`);
      }
      console.log("");
    });
}
