/**
 * Tailwind v4 @theme generator — emits a CSS file with Tailwind v4 syntax.
 *
 * Tailwind v4 replaces tailwind.config.js with CSS-first configuration:
 *   @theme {
 *     --color-primary: #0066ff;
 *     --spacing-md: 1rem;
 *     ...
 *   }
 *
 * This is the modern (2025+) target. tailwind.config.js is dead.
 */

import type { DesignToken } from "../engine/registry.js";

/**
 * Generate a Tailwind v4 CSS file with an @theme block mapped from tokens.
 *
 * Token name conventions:
 *   - `color.primary` → `--color-primary`
 *   - `spacing.md` → `--spacing-md`
 *   - `radius.lg` → `--radius-lg`
 *   - `shadow.card` → `--shadow-card`
 */
export function generateTailwindV4Theme(tokens: DesignToken[]): string {
  const lines: string[] = [];
  lines.push("/* Generated by Memoire — Tailwind v4 @theme block */");
  lines.push("/* Re-run `memi tokens` to update */");
  lines.push('@import "tailwindcss";');
  lines.push("");
  lines.push("@theme {");

  // Group tokens by type
  const colors = tokens.filter(t => t.type === "color");
  const spacing = tokens.filter(t => t.type === "spacing");
  const radii = tokens.filter(t => t.type === "radius");
  const shadows = tokens.filter(t => t.type === "shadow");
  const typography = tokens.filter(t => t.type === "typography");

  if (colors.length > 0) {
    lines.push("  /* Colors */");
    for (const t of colors) {
      const name = slugify(t.name);
      const value = firstValue(t);
      if (value !== undefined) lines.push(`  --color-${name}: ${value};`);
    }
    lines.push("");
  }

  if (spacing.length > 0) {
    lines.push("  /* Spacing */");
    for (const t of spacing) {
      const name = slugify(t.name);
      const value = normalizeSize(firstValue(t));
      if (value !== undefined) lines.push(`  --spacing-${name}: ${value};`);
    }
    lines.push("");
  }

  if (radii.length > 0) {
    lines.push("  /* Radii */");
    for (const t of radii) {
      const name = slugify(t.name);
      const value = normalizeSize(firstValue(t));
      if (value !== undefined) lines.push(`  --radius-${name}: ${value};`);
    }
    lines.push("");
  }

  if (shadows.length > 0) {
    lines.push("  /* Shadows */");
    for (const t of shadows) {
      const name = slugify(t.name);
      const value = firstValue(t);
      if (value !== undefined) lines.push(`  --shadow-${name}: ${value};`);
    }
    lines.push("");
  }

  if (typography.length > 0) {
    lines.push("  /* Typography */");
    for (const t of typography) {
      const name = slugify(t.name);
      // Typography tokens have compound values
      if (typeof t.values.fontFamily === "string") lines.push(`  --font-${name}: ${t.values.fontFamily};`);
      if (t.values.fontSize !== undefined) lines.push(`  --text-${name}: ${normalizeSize(t.values.fontSize) ?? t.values.fontSize};`);
    }
    lines.push("");
  }

  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

function firstValue(token: DesignToken): string | number | undefined {
  return token.values.default ?? token.values.Default ?? Object.values(token.values)[0];
}

function slugify(name: string): string {
  return name
    .replace(/^--/, "")
    .replace(/[^a-zA-Z0-9-_]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .toLowerCase();
}

function normalizeSize(value: string | number | undefined): string | undefined {
  if (value === undefined) return undefined;
  if (typeof value === "number") return `${value}px`;
  const s = String(value).trim();
  return /^\d+(\.\d+)?$/.test(s) ? `${s}px` : s;
}
